version: '3.8'

services:
  remix-app:
    container_name: remix-app
    image: remix-app
    hostname: remix-app
    build:
      context: .
      dockerfile: Dockerfile
      target: remix
    ports:
      - '3000:3000'

  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - remix-app
    ports:
      - 80:80
    links: 
      - remix-app:remix-app